//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.ncore.ServicedApi.CodeGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _servicedApiXmlFileTextBox_Text {
            get {
                return ((string)(this["_servicedApiXmlFileTextBox_Text"]));
            }
            set {
                this["_servicedApiXmlFileTextBox_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _outputPathRootTextBox_Text {
            get {
                return ((string)(this["_outputPathRootTextBox_Text"]));
            }
            set {
                this["_outputPathRootTextBox_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _generatorPluginComboBox_Selected {
            get {
                return ((string)(this["_generatorPluginComboBox_Selected"]));
            }
            set {
                this["_generatorPluginComboBox_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _stopOnGenerationErrorsCheckBox_Checked {
            get {
                return ((bool)(this["_stopOnGenerationErrorsCheckBox_Checked"]));
            }
            set {
                this["_stopOnGenerationErrorsCheckBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _showGenerationResultsWindowCheckBox_Checked {
            get {
                return ((bool)(this["_showGenerationResultsWindowCheckBox_Checked"]));
            }
            set {
                this["_showGenerationResultsWindowCheckBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _enableTemplateDebuggingCheckBox_Checked {
            get {
                return ((bool)(this["_enableTemplateDebuggingCheckBox_Checked"]));
            }
            set {
                this["_enableTemplateDebuggingCheckBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _runGeneratorSynchronouslyCheckBox_Checked {
            get {
                return ((bool)(this["_runGeneratorSynchronouslyCheckBox_Checked"]));
            }
            set {
                this["_runGeneratorSynchronouslyCheckBox_Checked"] = value;
            }
        }
    }
}
